#!/bin/bash
set -x
. config
#  Package zap2xml as a kodi addon that can be installed from a zip file
#
rm -rf tools.module.zap2xml
rm tools.module.zap2xml-*.zip
mkdir tools.module.zap2xml
cp -r base_addon/* tools.module.zap2xml
#
#  Populate the addon
#
cp ../*.py tools.module.zap2xml/
cp ../.zap2xmlrc tools.module.zap2xml/
#  todo - add the license files to keep everything on the up-n-up
# cp ../LICENSE  tools.module.zap2xml/LICENSE-zap2xml
#
# update the addon version number
sed -i tools.module.zap2xml/addon.xml -e 's/__VER__/'${ADDON_VERSION}'/g'
zip -r tools.module.zap2xml-${ADDON_VERSION}.zip tools.module.zap2xml/
exit 0
